services:
  postgres:
    image: ghcr.io/daemonless/immich-postgres:pkg
    network_mode: host
    environment:
      POSTGRES_USER: immich
      POSTGRES_PASSWORD: immich
      POSTGRES_DB: immich

  redis:
    image: ghcr.io/daemonless/redis:pkg
    network_mode: host

  immich:
    image: ${CIT_IMAGE:-ghcr.io/daemonless/immich-server:build}
    network_mode: host
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOSTNAME: 127.0.0.1
      DB_USERNAME: immich
      DB_PASSWORD: immich
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: 127.0.0.1
